trigger:
  branches:
    include:
      - master
      - develop
      - staging

variables:
  imageName: 'microservice'
  acrName: 'acrmicroservicesanti'
  resourceGroup: 'microservice-rg'
  clusterName: 'microservice-cluster'

stages:
  - stage: BuildAndTest
    displayName: Build & Test
    jobs:
      - job: Node
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Use Node.js'

          - script: npm ci
            displayName: 'Install dependencies'

          - script: npm test
            displayName: 'Run tests'

          - task: Docker@2
            displayName: 'Build and Push Docker Image'
            inputs:
              containerRegistry: 'ACR_CONNECTION'
              repository: $(imageName)
              command: buildAndPush
              Dockerfile: Dockerfile
              tags: |
                $(Build.SourceBranchName)-$(Build.BuildId)
                latest

  - stage: Deploy
    displayName: Deploy to AKS
    dependsOn: BuildAndTest
    jobs:
      - deployment: DeployToProduction
        displayName: Deploy to production
        condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
        environment: production
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'AZURE_CONNECTION'
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az aks get-credentials --resource-group $(resourceGroup) --name $(clusterName)
                      kubectl set image deployment/microservice microservice=$(acrName).azurecr.io/$(imageName):$(Build.SourceBranchName)-$(Build.BuildId)

      - deployment: DeployToDevelop
        displayName: Deploy to develop
        condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))
        environment: develop
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'AZURE_CONNECTION'
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az aks get-credentials --resource-group $(resourceGroup) --name $(clusterName)
                      kubectl set image deployment/microservice microservice=$(acrName).azurecr.io/$(imageName):$(Build.SourceBranchName)-$(Build.BuildId)

      - deployment: DeployToStaging
        displayName: Deploy to staging
        condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'staging'))
        environment: staging
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'AZURE_CONNECTION'
                    scriptType: bash
                    scriptLocation: inlineScript
                    inlineScript: |
                      az aks get-credentials --resource-group $(resourceGroup) --name $(clusterName)
                      kubectl set image deployment/microservice microservice=$(acrName).azurecr.io/$(imageName):$(Build.SourceBranchName)-$(Build.BuildId)
